"""Input and output helpers for coordinate files."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable


@dataclass(frozen=True)
class Atom:
    symbol: str
    x: float
    y: float
    z: float


def _parse_atom_line(line: str, line_number: int) -> Atom:
    parts = line.split()
    if len(parts) < 4:
        raise ValueError(f"Invalid coordinate line {line_number}: expected 'Element x y z'.")
    symbol = parts[0].strip()
    if not symbol:
        raise ValueError(f"Invalid coordinate line {line_number}: missing element symbol.")
    try:
        x, y, z = (float(parts[1]), float(parts[2]), float(parts[3]))
    except ValueError as exc:
        raise ValueError(f"Invalid coordinate line {line_number}: x/y/z must be floats.") from exc
    return Atom(symbol=symbol, x=x, y=y, z=z)


def read_xyz(path: str | Path) -> list[Atom]:
    """Read standard XYZ or simple 'Element x y z' coordinate files."""

    xyz_path = Path(path)
    if not xyz_path.exists():
        raise FileNotFoundError(f"XYZ file not found: {xyz_path}")

    raw_lines = xyz_path.read_text(encoding="utf-8").splitlines()
    if not raw_lines:
        raise ValueError(f"Empty XYZ file: {xyz_path}")

    first = raw_lines[0].strip()
    atom_lines: list[tuple[int, str]]
    if first:
        try:
            expected_count = int(first)
        except ValueError:
            expected_count = -1
        if expected_count >= 0:
            selected = raw_lines[2 : 2 + expected_count]
            nonempty = [(idx + 3, line.strip()) for idx, line in enumerate(selected) if line.strip()]
            if len(nonempty) != expected_count:
                raise ValueError(
                    f"XYZ atom count mismatch: header says {expected_count}, "
                    f"but {len(nonempty)} coordinate lines were found."
                )
            atom_lines = nonempty
        else:
            atom_lines = [(idx + 1, line.strip()) for idx, line in enumerate(raw_lines) if line.strip()]
    else:
        atom_lines = [(idx + 1, line.strip()) for idx, line in enumerate(raw_lines) if line.strip()]

    atoms = [_parse_atom_line(line, line_number) for line_number, line in atom_lines]
    if not atoms:
        raise ValueError(f"No atoms found in coordinate file: {xyz_path}")
    return atoms


def atoms_to_pyscf_atom_text(atoms: Iterable[Atom]) -> str:
    """Convert parsed atoms to a PySCF atom specification string."""

    lines = [f"{a.symbol:2s} {a.x: .12f} {a.y: .12f} {a.z: .12f}" for a in atoms]
    if not lines:
        raise ValueError("Cannot build PySCF atom text from an empty atom list.")
    return "\n".join(lines)


def write_mol_xyz(mol: Any, out_path: str | Path, comment: str = "") -> None:
    """Write a PySCF Mole-like object as XYZ."""

    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    coords = mol.atom_coords(unit="Angstrom")
    lines = [str(mol.natm), comment or "Generated by gpu4pyscf-h200-runner"]
    for i in range(mol.natm):
        symbol = mol.atom_symbol(i)
        x, y, z = coords[i]
        lines.append(f"{symbol:2s} {float(x): .12f} {float(y): .12f} {float(z): .12f}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_atoms_xyz(atoms: Iterable[Atom], out_path: str | Path, comment: str = "") -> None:
    """Write parsed atoms as XYZ."""

    atom_list = list(atoms)
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [str(len(atom_list)), comment or "Generated by gpu4pyscf-h200-runner"]
    lines.extend(f"{a.symbol:2s} {a.x: .12f} {a.y: .12f} {a.z: .12f}" for a in atom_list)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

